version: '3.0'
services:
  service:
    build:
      context: .
      dockerfile: Dockerfile_service
    command: '/app/docker/service/start-server.sh'
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      - DJANGO_ENV=${DJANGO_ENV}  # if you want to run daphne, set 'production'
      - REDIS_HOSTNAME=redis
      - REDIS_DB_NUMBER=0
      - REDIS_DB_PREFIX=local
      - PYTHONUNBUFFERED=1
    links:
      - redis
      - db

  service_nginx:
    build:
      context: ./docker/service_nginx
    command: '/start-nginx.sh'
    ports:
      - "8000:8000"
    links:
      - service

  vuejs:
    build:
      context: .
      dockerfile: Dockerfile_vuejs
    command: '/app/docker/vuejs/start-watch.sh'
    volumes:
      - .:/app
      #- ./application/static/assets:/app/application/vuejs/dist
      - node-modules-volume:/app/application/vuejs/node_modules

  redis:
    image: redis:3.2.4-alpine
    ports:
      - "6379:6379"

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: kanban

volumes:
  node-modules-volume:
